<a href="https://colab.research.google.com/github/IssabellaZ/MA3K7/blob/main/MA3K7_Assignment_2_grid_game.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import itertools as it
import numpy as np

def generate_matrices(n):
    # Generate all permutations of 0's and 1's given n even or odd

    if n%2 == 0:
        x = int(n**2/2)
        all_permute = set(it.permutations([0]*x+[1]*x))
    else:
        y = int((n**2-1)/2)
        permute1 = set(it.permutations([0]*y +[1]*(y+1)))
        permute2 = set(it.permutations([0]*(y+1)+[1]*y))

        # Combine the two sets of permutations
        all_permute = permute1.union(permute2)

    unique_matrices = {}

    count = 0

    for i,each in enumerate(all_permute):
        # Reshape the permutation
        matrix = np.array(each).reshape((n, n))
        determinant = np.linalg.det(matrix)

        if determinant == 0:
            count += 1
            unique_matrices.update({count:(determinant, matrix)})

    # print(unique_matrices)

    for i in range(len(unique_matrices)):
        print(f"Matrix {i+1}:")
        print(unique_matrices[i+1][1])
        print("Determinant:", unique_matrices[i+1][0])
        print()


generate_matrices(3)

Matrix 1:
[[1 1 1]
 [1 1 0]
 [0 0 0]]
Determinant: 0.0

Matrix 2:
[[0 0 1]
 [1 1 0]
 [1 1 0]]
Determinant: 0.0

Matrix 3:
[[0 0 0]
 [1 1 0]
 [1 1 1]]
Determinant: 0.0

Matrix 4:
[[0 1 0]
 [1 1 0]
 [1 1 0]]
Determinant: 0.0

Matrix 5:
[[1 1 0]
 [0 0 0]
 [1 1 1]]
Determinant: 0.0

Matrix 6:
[[0 1 0]
 [0 1 1]
 [0 0 1]]
Determinant: 0.0

Matrix 7:
[[1 1 0]
 [1 0 0]
 [0 1 0]]
Determinant: 0.0

Matrix 8:
[[0 0 1]
 [1 1 1]
 [0 0 0]]
Determinant: 0.0

Matrix 9:
[[0 0 0]
 [1 1 1]
 [1 0 1]]
Determinant: 0.0

Matrix 10:
[[0 0 0]
 [1 1 1]
 [1 1 0]]
Determinant: 0.0

Matrix 11:
[[0 1 1]
 [1 1 1]
 [0 0 0]]
Determinant: 0.0

Matrix 12:
[[1 1 1]
 [0 1 0]
 [0 1 0]]
Determinant: 0.0

Matrix 13:
[[0 1 0]
 [0 1 0]
 [1 1 0]]
Determinant: 0.0

Matrix 14:
[[0 0 0]
 [1 1 1]
 [0 0 1]]
Determinant: 0.0

Matrix 15:
[[1 0 1]
 [1 0 1]
 [0 1 0]]
Determinant: 0.0

Matrix 16:
[[0 0 0]
 [1 0 1]
 [0 1 1]]
Determinant: 0.0

Matrix 17:
[[0 1 0]
 [1 0 1]
 [0 1 0]]
Determinant: 0.0

Matrix 18:
[[0 0 0]
 [0 1 1]
 [1 1 0]]
D